# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 10

[[main]]
  name = "Work"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Journal"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

# -- Footer Menu --

[[footer]]
  name = "Journal RSS"
  pre = "rss"
  url = "/posts/index.xml"
  weight = 10
